services:
  client:
    build: ./client
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REACT_APP_API_URL=http://localhost:3000
    networks:
      - app-network
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb+srv://anvnt96:asdqwe123@cluster0.bs2jhhq.mongodb.net/Notes
    networks:
      - app-network

networks:
  app-network:
    driver: bridge