version: 2.1

orbs:
  node: circleci/node@5.1.0

commands:
  notify-telegram:
    parameters:
      status:
        type: string
      step:
        type: string
        default: "build"
    steps:
      - run:
          name: Notify Telegram
          when: always
          command: |
            if [ "<< parameters.status >>" = "success" ]; then
              EMOJI="✅"
              STATUS="thành công"
            else
              EMOJI="❌"
              STATUS="thất bại"
            fi
            
            COMMIT_MSG=$(git log -1 --pretty=%B | sed 's/"/\\"/g')
            COMMIT_HASH=$(git rev-parse --short HEAD)
            COMMIT_URL="https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/commit/$CIRCLE_SHA1"
            
            # Escape special characters and create message with proper line breaks
            MESSAGE=$(cat <<EOF
            ${EMOJI} <b>${CIRCLE_PROJECT_REPONAME}</b>
            
            🔄 <b>Trạng thái:</b> << parameters.step >> ${STATUS}
            👤 <b>Branch:</b> ${CIRCLE_BRANCH}
            🏗️ <b>Build:</b> #${CIRCLE_BUILD_NUM}
            📝 <b>Commit:</b> <a href="${COMMIT_URL}">${COMMIT_HASH}</a>
            💬 <b>Message:</b> ${COMMIT_MSG}
            ⏱️ <b>Thời gian:</b> $(date '+%Y-%m-%d %H:%M:%S')
EOF
            )
            
            # URL encode the message
            encoded_message=$(echo "$MESSAGE" | jq -sRr @uri)
            
            # Send to Telegram
            curl -s "https://api.telegram.org/bot7801299262:AAFTUsvVxL59EzZHQfAcdLYOgb4kK5B42Fg/sendMessage" \
              --data-urlencode "chat_id=6894773989" \
              --data-urlencode "text=$MESSAGE" \
              --data-urlencode "parse_mode=HTML"

jobs:
  build:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - notify-telegram:
          status: success
          step: "Build"

  deploy:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: |
            echo "Deploying to production..."
            if curl -X POST \
              -H "Accept: application/json" \
              -H "Content-Type: application/json" \
              "https://api.render.com/deploy/srv-ctl3cnlds78s73c3ktdg?key=rnd_aNr7V6i33gzm6QE3BeyGvJwwmohf"; then
              # If deploy succeeds
              notify-telegram:
                status: success
                step: "Deploy"
            else
              # If deploy fails
              notify-telegram:
                status: failed
                step: "Deploy"
              exit 1
            fi
      - notify-telegram:
          status: success
          step: "Deploy"
          when: on_success
      - notify-telegram:
          status: failed
          step: "Deploy"
          when: on_fail

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - main
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
                - main
                - master