
version: 2.1

orbs:
  node: circleci/node@5.1.0

commands:
  notify-telegram:
    parameters:
      status:
        type: string
    steps:
      - run:
          name: Notify Telegram
          command: |
            if [ "<< parameters.status >>" = "success" ]; then
              MESSAGE="✅ $CIRCLE_PROJECT_REPONAME: Build #$CIRCLE_BUILD_NUM passed on $CIRCLE_BRANCH"
            else
              MESSAGE="❌ $CIRCLE_PROJECT_REPONAME: Build #$CIRCLE_BUILD_NUM failed on $CIRCLE_BRANCH"
            fi
            curl -s -X POST https://api.telegram.org/bot7801299262:AAFTUsvVxL59EzZHQfAcdLYOgb4kK5B42Fg/sendMessage -d chat_id=6894773989 -d text="$MESSAGE" -d parse_mode="HTML"
          when: always

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.0
    working_directory: ~/project/server
    steps:
      - checkout:
          path: ~/project
      - node/install-packages
      - run:
          name: Run Tests
          command: npm test
      - notify-telegram:
          status: success

  deploy:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: |
            echo "Deploying to production..."
            if [ "${CIRCLE_BRANCH}" = "master" ] || [ "${CIRCLE_BRANCH}" = "main" ]; then
              curl -X POST \
                -H "Accept: application/json" \
                -H "Content-Type: application/json" \
                "https://api.render.com/deploy/srv-ctl3cnlds78s73c3ktdg?key=rnd_aNr7V6i33gzm6QE3BeyGvJwwmohf"
              notify-telegram:
                status: success
            fi

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: 
                - main
                - master
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: 
                - main
                - master