version: 2.1

orbs:
  node: circleci/node@5.1.0

commands:
  notify-telegram:
    parameters:
      status:
        type: string
      step:
        type: string
        default: "build"
    steps:
      - run:
          name: Notify Telegram
          when: always
          command: |
            if [ "<< parameters.status >>" = "success" ]; then
              EMOJI="✅"
              STATUS="thành công"
            else
              EMOJI="❌"
              STATUS="thất bại"
            fi
            
            COMMIT_MSG=$(git log -1 --pretty=%B)
            COMMIT_HASH=$(git rev-parse --short HEAD)
            COMMIT_URL="https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/commit/$CIRCLE_SHA1"
            
            MESSAGE="${EMOJI} *${CIRCLE_PROJECT_REPONAME}*\n\n🔄 *Trạng thái*: << parameters.step >> ${STATUS}\n👤 *Branch*: ${CIRCLE_BRANCH}\n🏗️ *Build*: #${CIRCLE_BUILD_NUM}\n📝 *Commit*: <a href='${COMMIT_URL}'>${COMMIT_HASH}</a>\n💬 *Message*: ${COMMIT_MSG}\n⏱️ *Thời gian*: $(date '+%Y-%m-%d %H:%M:%S')"
            
            curl -s -X POST "https://api.telegram.org/bot7801299262:AAFTUsvVxL59EzZHQfAcdLYOgb4kK5B42Fg/sendMessage" \
              -d "chat_id=6894773989" \
              -d "text=${MESSAGE}" \
              -d "parse_mode=HTML"

jobs:
  build:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - notify-telegram:
          status: success
          step: "Build"

  deploy:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: |
            echo "Deploying to production..."
            curl -X POST \
              -H "Accept: application/json" \
              -H "Content-Type: application/json" \
              "https://api.render.com/deploy/srv-ctl3cnlds78s73c3ktdg?key=rnd_aNr7V6i33gzm6QE3BeyGvJwwmohf"
      - notify-telegram:
          status: success
          step: "Deploy"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - main
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
                - main
                - master