version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: |
            sudo npm install -g npm@8
            npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests
          command: npm test

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy to Render
          command: |
            echo "Deploying to Render..."
            curl -X POST \
              -H "Accept: application/json" \
              -H "Content-Type: application/json" \
              "https://api.render.com/deploy/$RENDER_SERVICE_ID?key=$RENDER_API_KEY"
            echo "Deployment triggered successfully"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main